"""Set nullable=True for task_descr. & due_date

Revision ID: 242c9c7f6381
Revises: 
Create Date: 2023-04-13 18:37:30.405907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242c9c7f6381'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('task_description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('task_description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
